### ISSUE TITLE
Streamline Hardhat Smart Contract Verification Process Similar to Sourcify

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#768] opened 2023-11-23 23:05 UTC
### Problem

The current smart contract verification process on Hedera Explorer requires users to upload both the metadata file and the Solidity source code files. This dual requirement can be cumbersome and less efficient for developers, especially those accustomed to Sourcify's simpler verification process that only necessitates the Hardhat `artifacts/build-info` JSON file be uploaded as detailed in the [sourcify docs](https://docs.sourcify.dev/docs/how-to-verify/#with-hardhat-output). The additional steps of separately preparing and uploading source code files add complexity and time to the verification process.

### Solution

I propose enhancing the smart contract verification process on the hedera explorer by adopting a method similar to Sourcify's. This enhancement would allow users to verify their smart contracts using only the Hardhat `build-info` JSON file. The JSON file contains all necessary information, including the bytecode, ABI, metadata, and Solidity source code. By extracting this data directly from the JSON file, the verification process can be significantly streamlined, making it more user-friendly and efficient. This change would simplify the workflow for developers, aligning Hedera's verification process more closely with the efficient practices used in other blockchain ecosystems.

**Comment by svienot** [comment] 2023-11-24 10:05
Hello @mshakeg - The HardHat build-info JSON format is indeed already supported. Just drop the file located in `artifacts/build-info/` and things should work.

**Comment by svienot** [comment] 2023-11-24 13:29
Would you mind attaching a zip of {solidity source, build-info JSON} here so we can investigate ?

**Comment by mshakeg** [comment] 2023-11-24 14:35
@svienot sure, I've attached the same json file that I uploaded when attempting to verify the `0.0.5965242` contract(i.e. the `UV3Math` contract) as that is the file linked in the `UV3Math.dbg.json` file:
```
{
  "_format": "hh-sol-dbg-1",
  "buildInfo": "../../../build-info/1560b26973c074a141d5e6c39a4f80cf.json"
}
```


[1560b26973c074a141d5e6c39a4f80cf.json](https://github.com/hashgraph/hedera-mirror-node-explorer/files/13460105/1560b26973c074a141d5e6c39a4f80cf.json)

**Comment by svienot** [comment] 2023-11-24 16:51
Thank you. I confirm I can reproduce the issue.

**Comment by ericleponner** [comment] 2023-11-28 15:10
I observe that UV3Math bytecodes from mirror node and from json file do not match:
- `0x73fbf38920ccbcff7268ad714ae5f9fad6df60706530146080604…` // mirror node
- `0x73000000000000000000000000000000000000000030146080604…` // json file

@mshakeg Do you know how [0.0.5965242](https://hashscan.io/testnet/contract/0.0.5965242) was deployed on `testnet` ?
Is it using HardHat (and the json file above) ? Or another tooling ?

**Comment by mshakeg** [comment] 2023-11-28 16:51
@ericleponner if you [compare](https://countwordsfree.com/comparetexts) the 2 bytecode strings you'll notice that the only difference is `0xfbf38920ccbcff7268ad714ae5f9fad6df607065`. This is the evm address for the [0.0.5965242](https://hashscan.io/testnet/contract/0.0.5965242) contract.

IMU since UV3Math is a solidity `library` it is expected for the library address to follow immediately after `0x73`. So I don't see any issue here.

**Comment by ericleponner** [comment] 2023-11-28 17:13
I don't see issue either. Thanks for the hints.

**Comment by mshakeg** [comment] 2023-11-29 09:44
@ericleponner thanks for the fix, I was able to verify a newer deployment of the [UV3Math](https://hashscan.io/testnet/contract/0.0.5989890) library.

However I have another [ICHIVaultDeployer](https://hashscan.io/testnet/contract/0.0.5989914) library that I cannot verify using the `build-info` artifact attached below. I suspect that the verification fails because the `ICHIVaultDeployer` library is linked to the `UV3Math` library however the `ICHIVaultDeployer` bytecode in the build-info artifact has `0x00...` placeholders(i.e. `address(0)`) instead of the `UV3Math` library address i.e. `0xd4c0e17794a83665b5a61836333610d2d48dfd7f`, and so if you search the deployed bytecode of the `ICHIVaultDeployer` library for `d4c0e17794a83665b5a61836333610d2d48dfd7f` you'll see numerous occurrences of the `UV3Math` address all preceded with `73`.

[804621e70b45426caf3f71859dbea803.json](https://github.com/hashgraph/hedera-mirror-node-explorer/files/13498751/804621e70b45426caf3f71859dbea803.json)

**Comment by mshakeg** [comment] 2023-11-29 09:49
[In hardhat](https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-verify#usage) if a contract has a `constructor` you'd specify an `arguments.js` file with the constructor values and if the contract/library is linked to at least 1 library you'd specify a `libraries.js` file. These 2 files will then be used to help verify the contract.

**Comment by ericleponner** [comment] 2023-11-29 10:19
@mshakeg Forget my previous request (new issue) : we'll continue on this one.

**Comment by mshakeg** [comment] 2023-12-06 15:02
@ericleponner sourcify doesn't support the Hedera testnet, but I suppose we could for our mainnet deployment, though ideally we'd want to have our contracts verified on hashscan.

**Comment by ericleponner** [comment] 2023-12-06 15:05
@mshakeg 
I meant Sourcify instance underlying Explorer:  https://verify.hashscan.io .
This one supports `testnet`.

**Comment by ericleponner** [comment] 2023-12-07 13:56
@mshakeg 
I guess we're facing to a limitation of core Sourcify. 
Instance of Sourcify deployed by Hedera is functionally equivalent to the instance operated by Sourcify team.
If you're facing bugs or have feature requests, feel free to open issues on Hedera sourcify repo:
https://github.com/hashgraph/hedera-sourcify

**Comment by svienot** [comment] 2023-12-28 18:51
Since PR #811 the verification flow in the Explorer should accept the input as the hedera sourcify instance. So I am closing this issue. Any further discrepancy in this area will be logged as new issue.

**Closed by svienot** 2023-12-28 18:51 UTC
Labels: enhancement
