### ISSUE TITLE
Hashscan - Verify contract | Analysis failed

### ISSUE THREAD

**Issue by se7enarianelabs** [hashgraph/hedera-mirror-node-explorer#847] opened 2024-01-16 13:13 UTC
### Description

When attempting to verify the contract code (0.0.4414077) after uploading the .sol directory, I encounter the following message: 'Analysis failed.' In the console, I observe the following error:
```
TypeError:
    <anonymous> https://hashscan.io/:4
lockdown-install.js:1:94626
    functors moz-extension://cf59f65c-2346-4d61-b1cc-8e5e4d308209/lockdown-install.js:1
```

[AllowListGateContract.json](https://github.com/hashgraph/hedera-mirror-node-explorer/files/13950395/AllowListGateContract.json)
<img width="760" alt="Screenshot 2024-01-16 at 14 07 53" src="https://github.com/hashgraph/hedera-mirror-node-explorer/assets/101180841/5ce220b8-81b1-4108-8c28-0e1002759539">

### Steps to reproduce

1. Navigate to the website https://hashscan.io/mainnet/contract/0.0.4414077
2. Select the option to verify a contract code.
3. Input the contract code "0.0.4414077" for verification.
4. Upload the .sol directory associated with the contract.
5. Observe the displayed message indicating that the analysis has failed.
6. Open the browser console to view detailed error message

### Hedera network

other

### Version

v0.1.0

### Operating system

macOS

**Comment by ericleponner** [comment] 2024-01-17 11:27
Hi @se7enarianelabs, thanks for reporting.
Could you provide `AllowListContract.sol` ?

**Comment by se7enarianelabs** [comment] 2024-01-17 13:14
Sure, 
```
pragma solidity ^0.8.0;

import "./../Structs.sol";
import "./../interfaces/IValidationGate.sol";
import "./../commons/Common.sol";
import "@openzeppelin/contracts/utils/cryptography/MerkleProof.sol";
import "../interfaces/IExtension.sol";

/**
 * @author  Piotr Swierzy
 * @title   AllowListGateContract
 * @dev     This is gates validates if the sender is in the allow list
 * @notice  .
 */

contract AllowListGateContract is
    IValidationGate,
    Common,
    IExtension
{
    string public constant EXTENSION_NAME = "ALLOW_LIST_GATE";


    /**
     * @notice  .
     * @dev     This function validates if the sender address is in the allow list
     * @param   params claiming params
     * @return  result  .
     */
    function validate(
        GetNFTParams memory params
    ) external payable returns (bool result) {
        bytes32 leaf = keccak256(abi.encodePacked(msg.sender));
        result = MerkleProof.verify(
            params.merkleProof,
            getConfig().allowListMerkleRoot,
            leaf
        );
        require(result, string(abi.encodePacked(VALIDATION_ERROR_MESSAGE_PREFIX, EXTENSION_NAME)));

    }

    /**
     * @dev     Updates the allowListMerkleRoot
     * @param   newAllowListMerkleRoot new value of the allowListMerkleRoot
     */
    function setConfigAllowListMerkleRoot(bytes32 newAllowListMerkleRoot) external onlyOwner {
        getConfig().allowListMerkleRoot = newAllowListMerkleRoot;
    }

    /**
     * @dev     Returns the configured allowListMerkleRoot
     * @return  bytes32 configured allowListMerkleRoot
     */
    function getConfigAllowListMerkleRoot() public view returns (bytes32) {
        return getConfig().allowListMerkleRoot;
    }


    /**
     * @notice  This hook does nothing in this gate
     * @dev     .
     * @param   params  .
     */
    function hookAfterDistributed(GetNFTParams memory params) external payable {
        return;
    }

    /**
     * @dev     Get the module name
     * @return  Module name
     */
    function getExtensionName() external view returns (string memory) {
        return EXTENSION_NAME;
    }
}

```
https://github.com/hashgraph/hedera-claimbox-contracts/blob/main/contracts/gates/AllowListContract.sol

**Comment by ericleponner** [comment] 2024-01-23 15:32
`AllowListContract.sol` imports many other files (`Struct.sol`, `IValidationGate.sol` …) : would it be possible to have all the solidity sources ? Without them we won't be able to reproduce the pb.

Also could you describe your gestures : do you drop a single folder containing all the sources and metadata ? Or do you drop them one by one ?

Regarding these messages:
```
TypeError:
    <anonymous> https://hashscan.io/:4
lockdown-install.js:1:94626
    functors moz-extension://cf59f65c-2346-4d61-b1cc-8e5e4d308209/lockdown-install.js:1
```
I don't think they come from HashScan. 
It looks like they are issued by a FireFox extension (`moz-extension://` prefix): may be a wallet ?

**Comment by Neurone** [comment] 2024-01-24 11:10
I tried to verify the contract and everything worked (see now https://hashscan.io/mainnet/contract/0.0.4414077?p=1&k=1705394073.960688003)

I think the problem was you were using the partial json ([AllowListGateContract.json](https://github.com/hashgraph/hedera-mirror-node-explorer/files/13950395/AllowListGateContract.json)) and not the complete json for metadata.

My flow was this:

1. clone the repo (https://github.com/hashgraph/hedera-claimbox-contracts/tree/main)
2. npm i
3. update .env
4. npx hardhat compile
5. upload the generated metadata (./artifacts/build-info/252b358f334e40c3af95650a4970edda.json)
6. upload all the files under ./contracts
7. verify

**Comment by svienot** [comment] 2024-01-30 18:51
- Closing this issue since the verification failure was cased by incomplete/incorrect user input.
- Capturing the fact there is room for improvement in the Verification Dialog in #881

**Closed by svienot** 2024-01-30 18:51 UTC
Labels: bug
