### ISSUE TITLE
Restyle and bring event logs component to contract level

### ISSUE THREAD

**Issue by quiet-node** [hashgraph/hedera-mirror-node-explorer#763] opened 2023-11-22 17:47 UTC
### Problem

The new event logs component is proposed to be changed to a new layout, and also be brought to contract detail page.

### Solution

- Restyle the current layout
- Bring the component to Contract Detail page

**Comment by SimiHunjan** [comment] 2023-12-01 16:28
close as duplicate of https://github.com/hashgraph/hedera-mirror-node-explorer/issues/729

**Closed by SimiHunjan** 2023-12-01 16:28 UTC
Labels: enhancement
