### ISSUE TITLE
use html anchor element for all internal links

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-mirror-node-explorer#447] opened 2023-02-15 16:13 UTC
### Problem

The mirror node explorer does not use the HTML anchor element for all internal links, it is used for example used to "Show associated contract" as can be seen [here](https://hashscan.io/testnet/account/0.0.3485444?p2=1), however is not used in all the following:
* Top Nav Bar
* Each record in the "Recent Transactions" table for an Account or Contract

### Solution

See abover

**Comment by svienot** [comment] 2023-03-09 15:27
Linked by mistake to PR #484 (which was in fact related to Issue #477).

**Comment by svienot** [comment] 2023-04-03 18:45
I had meant to comment on this and forgot to do so...
Click on table entries is managed by the Oruga table component we use, so we do not have full control of that.
We tried to detect modifiers to allow the user to do Ctrl-click or Cmd-click to navigate in a new tab, but there is a bug/limitation in the Oruga component preventing us to do so.

**Comment by mshakeg** [comment] 2023-04-03 18:49
@svienot I see, I don't really have much context, but do you think it would be a good idea to create an issue on the [oruga repo](https://github.com/oruga-ui/oruga/issues) and hopefully if it's resolved soon this functionality can be implemented on the explorer.

**Comment by svienot** [comment] 2023-04-04 14:51
I just opened this issue in the Oruga repository:  [Key Modifiers are not supported by OTable @click directive](https://github.com/oruga-ui/oruga/issues/510)

**Comment by svienot** [comment] 2023-05-02 18:13
Feel free to re-open (or open a new issue). However, beware that this won't be using regular anchor elements in tables, but instead catching modifier+click events to navigate to the details page in a new tab.

**Comment by mshakeg** [comment] 2023-05-02 18:29
@svienot i don't think I have permissions to reopen.

Can you elaborate on the effective difference? So long as I can right click and open in new tab then that works for me.

**Comment by svienot** [comment] 2023-05-02 21:54
I mean this would not be an HTML <a> element underneath, it would not highlight the link in the status bar, and you would not get the context menu you get usually with an anchor. 
What you would get, is the ability to open the details page in a new tab by doing ctrl-click on windows or cmd-click on mac.

**Comment by mshakeg** [comment] 2023-05-03 06:14
@svienot I see, is it impossible to make it an anchor element? I haven't worked with Vue, but in React at least in all the UI libraries I've worked with, it's straightforward to style a component(which by default is a `div`) as any other HTML element.

**Comment by svienot** [comment] 2023-05-03 07:35
The issue is that we do not want here to replace each cell element by an anchor. This is a table component where we want to process click events _on an entire row._

**Comment by svienot** [comment] 2023-05-11 14:02
> Could the same not be done on Hashscan?
We could. It is simply not the current design of the tables. 
In almost all of the tables, clicking on the whole row triggers navigation to the details of the entity represented in that row.

**Comment by mshakeg** [comment] 2023-05-11 14:08
@svienot Etherscan is consistent as far as I can tell no table has an entire row which is clickable. IMO that would be a good design choice for the tables on Hashscan as well, as all tables likely have at least 2 things that could be navigable.

**Comment by svienot** [comment] 2023-06-14 14:53
With the changes brought by #642, which allow to navigate from a table to a details page in a new tab, the expected functionality is there.  We might in the future revisit our table design to replace the current Oruga-based navigation by anchors but not in the foreseeable future, so I am closing this issue for now.

**Closed by svienot** 2023-06-14 14:53 UTC
Labels: enhancement, P1
